name: "GLM 4.6 (Z.ai coding plan)"
version: 1.0.0
schema: v1
models:
  - name: GLM 4.6
    provider: openai
    apiBase: https://api.z.ai/api/coding/paas/v4
    model: GLM-4.6
    apiKey: ${{ inputs.PROVIDER_API_KEY }}
  